name: Deploy to EC2
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          Add CodeQL workflow
